name:  Backend CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name : Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Start PostgreSQL
        working-directory: .
        run: docker compose up -d postgres

      - name: Run tests
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          GITHUB_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          TOKEN_ENCRYPTOR_PASSWORD: ${{ secrets.TOKEN_ENCRYPTOR_PASSWORD }}
          TOKEN_ENCRYPTOR_SALT: ${{ secrets.TOKEN_ENCRYPTOR_SALT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        run: ./mvnw test

      - name: Build application
        run: ./mvnw clean package -DskipTests
